# Generated by Django 3.0.7 on 2021-10-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='status',
        ),
    ]
